### ISSUE TITLE
Fix subheader layout

### ISSUE THREAD

**Issue by PBruk** [MITLibraries/MITLibraries-news#15]

**Comment by PBruk** [comment]
There is a bad break between the left and right sections of the subheader between tablet-sized breakpoints

**Comment by matt-bernhardt** [comment]
Is there a list of breakpoints for the theme anywhere?

**Comment by PBruk** [comment]
I doubt it. But, anyways, the problem was that both divs had a class of col-sm-12, which forced widths of 100% an any screen below...780 or so.

**Comment by darcyduke** [comment]
Talked with Phillip - on the mobile menu he is going to change "News home" to just "Home"

**Comment by PBruk** [comment]
Fixed in WP interface.

**Comment by matt-bernhardt** [comment]
Closing in consultation with @darcyduke - didn't require a code change
