### ISSUE TITLE
Individiual event: next to the event in orange, it now says "event date" but it should not.

### ISSUE THREAD

**Issue by darcyduke** [MITLibraries/MITLibraries-news#19]

**Comment by PBruk** [comment]
Fixed.

**Comment by darcyduke** [comment]
We changed this so that it DOES say that, but is formatted differently.

**Comment by matt-bernhardt** [comment]
What code change implements this fix? I don't see a commit affiliated with this issue anywhere.

**Comment by darcyduke** [comment]
Actually, we decided to ax this change, I was wrong. So mark it however you want to make that clear?

Darcy

**Comment by matt-bernhardt** [comment]
Okay - I'm marking this as closed then.
