### ISSUE TITLE
Byline oddity when post is published via scheduler

### ISSUE THREAD

**Issue by hartmans7** [MITLibraries/MITLibraries-news#29]
Brigham has started using the timed publishing function in WP. When she does this, it makes the author byline not clickable (though does keep the attribution correct).

**Comment by matt-bernhardt** [comment]
Is there an example post where I can see this in action?

**Comment by hartmans7** [comment]
Phillip and I talked this through a bit and discovered this was being caused by another issue. Should I have updated the waffle/issue -- or is that something you/phillip do as these things are discussed?

**Comment by matt-bernhardt** [comment]
No worries - one of us will update the issue as it works its way through the process. I'll check with Phillip.

**Comment by frrrances** [comment]
This may no longer be an issue. I'm closing this and if it comes back up, we can reopen.
