### ISSUE TITLE
Card composition changes

### ISSUE THREAD

**Issue by matt-bernhardt** [MITLibraries/MITLibraries-news#3]
* [ ] Make calendar icon same size as text next to it; if not exact, center horizontally
* [ ] Calendar icon not displaying
* [ ] Put event date under subtitle
* [ ] More space needed between main title and subtitle (use Moth design)
* [ ] Make subtitle be the same font color as main text (this makes it not quite so heavy/bold compared to title)
* [ ] Align right edge of big spotlight image with right edge of second box below it

Basecamp: https://basecamp.com/2612667/projects/6763762/todos/164761529

**Comment by matt-bernhardt** [comment]
This is an option for multiple small to-do items in a single issue

**Comment by PBruk** [comment]
Have made several composition changes and shown the group

**Comment by darcyduke** [comment]
A couple FF issues:
* [ ]  Calendar icon not displaying
* [ ]  "+*-" showing before some of the excerpt text (see "MIT Faculty Open Access Policy Yields...") - I feel like we saw this before a long time back?

Can we get the right edge of the big spotlight photo to align with the right edge of the 2nd box below it? I assume we would do this by making that image smaller (so the cropping tool would need to be adjusted too).

**Comment by matt-bernhardt** [comment]
Two brief notes:
1) The `+*-` characters have to do with the AddThis plugin. I do remember investigating this before, but can't find a record of it on Basecamp or here on GitHub. I'll create a separate issue momentarily for this bug, as it isn't related to the work of this ticket.
2) Checkboxes in issue comments are helpful, but only those in the first comment will be reflected in the list of issues. Should I edit my initial comment with the calendar icon one, or is it fine to let it live where it is?

**Comment by matt-bernhardt** [comment]
The `+*-` characters are recorded under issue #17 - so further discussion on that problem should be over there.

**Comment by darcyduke** [comment]
Yes, let's move the calendar to your check boxes. Maybe make a check box for aligning the large image too?

**Comment by matt-bernhardt** [comment]
Adjusted

**Comment by matt-bernhardt** [comment]
Closing in consultation with @darcyduke
