### ISSUE TITLE
Event card is too small

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITLibraries-news#32]
The cards on the "Classes & events" page seem to be smaller than the ones elsewhere on the News site and show a summary where the events cards on the full News site do not. Here are screenshots...

Events (needs to be fixed):
![events-cards](https://cloud.githubusercontent.com/assets/4327102/12754093/e975ecf2-c997-11e5-8957-b6ba68f844bf.png)

News (correct): 
![news-cards](https://cloud.githubusercontent.com/assets/4327102/12754105/f28d596a-c997-11e5-96be-3079df3d8512.png)

It would be good to have the cards all using the same code if they are not already.

**Comment by PBruk** [comment]
Fix has been made...

**Comment by frrrances** [comment]
Thanks @PBruk! Can you let me know when it's on -test to review?

**Comment by matt-bernhardt** [comment]
Are there any other changes that we should bundle with this fix? I have one or two things I can append to this, and can theoretically deploy this branch to -test later today
