### ISSUE TITLE
Fix blockquote formatting

### ISSUE THREAD

**Issue by darcyduke** [MITLibraries/MITLibraries-news#5]
A correspondent recently used the “block quote” formatting option and it looked terrible with too much space above and below the block quote. Can we format it so it looks reasonable? There is way too much space above and below the quote – there should only be one blank line’s worth of space. Here is an example: 
https://libraries-dev.mit.edu/news/testing-block-quote/19353/

**Comment by PBruk** [comment]
I think I made proper spacing adjustments and also, I added padding to bottom of section for the text to breathe a bit.

**Comment by matt-bernhardt** [comment]
@PBruk were there code changes that fixed this issue, or was it all done via the WP interface? I don't see a commit affiliated with this issue.

**Comment by PBruk** [comment]
I'll have to go back and see what I did exactly... I can't imagine it was purely WP interface.

**Comment by PBruk** [comment]
After review, we realized that whatever changes had been made, they had been overwritten, so... blockquote formatting should be good now.
