### ISSUE TITLE
Social media icons not appearing on "In the news" page

### ISSUE THREAD

**Issue by matt-bernhardt** [MITLibraries/MITLibraries-news#57]
At least several browsers (Chrome and IE) are not loading the social media icons in the sidebar correctly.

![2016-06-06_12-16-11](https://cloud.githubusercontent.com/assets/1403248/15829181/900dab18-2be0-11e6-87d3-768c1bf1fed7.png)

Live page at https://libraries.mit.edu/news/in-the-media/

**Comment by frrrances** [comment]
See related issue https://github.com/MITLibraries/MITLibraries-child/issues/15

**Comment by PBruk** [comment]
To get the actual social media icons to appear, not just chevron-circle-right, this HTML needs to be added to widget, with a widget css class of "connect-widget" : 


```
> <div>
> <span class="twitter-connect"><a href="#">[twitter-handle-goes-here]</a></span >
> <span class="fb-connect"><a href="#">[facebook-name-goes-here]</a></span>
> <span class="email-connect"><a href="#">[email-address-goes-here]</a></span>
> </div>
```

I will add other social media icons to the sidebar.scss file, as well, such as instagram and pinterest and... whatever other options might be needed. So those will be called the same, just replace social media type, as needed in span class that calls the icon.

**Comment by PBruk** [comment]
I guess, this is still missing?

![in-the-media](https://cloud.githubusercontent.com/assets/1832277/16288728/164d1a68-38bd-11e6-97bf-d7c989dd15a0.png)

**Comment by matt-bernhardt** [comment]
The markup mentioned above doesn't seem to be quite enough to achieve the desired display. With a widget markup of
```
<div>
<span class="twitter-connect"><a href="http://twitter.com/mitlibraries">Twitter</a></span>
<span class="fb-connect"><a href="https://www.facebook.com/mitlib">Facebook</a></span>
<span class="instagram-connect"><a href="http://instagram.com/mitlibraries">Instagram</a></span>
</div>
```
...and the class `connect-widget` added to the widget, I see the following in Chrome:
![image](https://cloud.githubusercontent.com/assets/1403248/18058444/5f618e82-6de2-11e6-8999-7c25d8e19486.png)

**Comment by matt-bernhardt** [comment]
Making the widget markup:
```
<div>
<p><span class="twitter-connect"><a href="http://twitter.com/mitlibraries">Twitter</a></span></p>
<p><span class="fb-connect"><a href="https://www.facebook.com/mitlib">Facebook</a></span></p>
<p><span class="instagram-connect"><a href="http://instagram.com/mitlibraries">Instagram</a></span></p>
</div>
```
... however produces the following screenshot:

![image](https://cloud.githubusercontent.com/assets/1403248/18058502/b25b904c-6de2-11e6-8566-5b4d8638a415.png)
