### ISSUE TITLE
Make admins of new site have permissions currently given to super-admins

### ISSUE THREAD

**Issue by darcyduke** [MITLibraries/MITLibraries-news#6]
We want the new communications officer to have all the permissions as a regular "admin" of the site that the super-admins have without making him/her a super-admin of all the sites (many things are hidden from correspondents, including being able to add Bibliotech posts). Melissa tried to do this, but couldn't make it work. Ask Darcy or Stephanie if it's not clear what those permissions are.

**Comment by darcyduke** [comment]
Basecamp: https://basecamp.com/2612667/projects/6763762/todos/161668495

**Comment by PBruk** [comment]
These should all match now...
