### ISSUE TITLE
Limit image upload size

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITLibraries-news#61]
There is no limit on the size of images added to posts currently, and it would be better to have a limit to let people know their image is too big for web. We should limit image uploads to 2MB.

**Comment by PBruk** [comment]
This is done in WP Admin.

Steps:
1. At the top, hover over My Sites and then click Network Admin.
2. At the left, hover over Settings and then click Network Settings.
3. Scroll to the bottom of the page and change the Max upload file size to 2000 KB.
4. Click Save Changes.

**Comment by frrrances** [comment]
TIL! Thanks @PBruk!
