### ISSUE TITLE
Add/remove spotlight categories

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITLibraries-news#65]
Brigham would like different spotlight categories. Please add these: 

- Featured story
- Featured video
- In the media
- Check it out

They should all act like the others – and have the star icon, which I believe is the icon used for everything except for Update. 

And remove these: 
- Fact
- Featured location

If posts exist in these, they can be moved over to a different category.

**Comment by matt-bernhardt** [comment]
I'm going to open a different issue around this problem. The branch as proposed should move forward in the name of getting Brigham the changes she's asked for - but in the long run these categories shouldn't be hard-coded into templates like this - it guarantees that future development work is needed when the categories need to change.

**Comment by frrrances** [comment]
sounds good @matt-bernhardt - let me know if you need any help.
